environment: production
chdir: /home/pankaj/public_html/cinchnotes/current/
address: 127.0.0.1
user: acoplet
group: acoplet
port: 8000
pid: /home/pankaj/public_html/cinchnotes/current/tmp/thin.pid
rackup: /home/pankaj/public_html/cinchnotes/current/config.ru
log: /home/pankaj/public_html/cinchnotes/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true

