environment: production
chdir: /var/www/apps/cinch-notes/current/
address: 127.0.0.1
user: acoplet
group: acoplet
port: 8000
pid: /var/www/apps/cinch-notes/current/tmp/thin.pid
rackup: /var/www/apps/cinch-notes/current/config.ru
log: /var/www/apps/cinch-notes/current/log/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true

